name: Publish to crates.io

on:
  workflow_call:
    secrets:
      CRATES_TOKEN:
        required: true
      BOT_GITHUB_TOKEN:
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@1.78.0
    - name: Publish to crates.io.
      run: |
        cargo publish --token ${CRATES_TOKEN} -p okkomm-rs
      env:
        CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}    
  release:
      name: Release
      runs-on: ubuntu-latest
      needs: publish
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Release
          uses: actions/create-release@latest
          env:
            GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: ${{ github.ref }}
            draft: true
            prerelease: false